export const tarotDeck = [
    // Major Arcana
    {id: 1, name: "The Fool", image: "./public/images/the_fool.png", arcana: "Major"},
    {id: 2, name: "The Magician", image: "./public/images/the_magician.png", arcana: "Major"},
    {id: 3, name: "The High Priestess", image: "./public/images/the_high_priestess.png", arcana: "Major"},
    {id: 4, name: "The Empress", image: "./public/images/the_empress.png", arcana: "Major"},
    {id: 5, name: "The Emperor", image: "./public/images/the_emperor.png", arcana: "Major"},
    {id: 6, name: "The Hierophant", image: "./public/images/the_hierophant.png", arcana: "Major"},
    {id: 7, name: "The Lovers", image: "./public/images/the_lovers.png", arcana: "Major"},
    {id: 8, name: "The Chariot", image: "./public/images/the_chariot.png", arcana: "Major"},
    {id: 9, name: "Strength", image: "./public/images/strength.png", arcana: "Major"},
    {id: 10, name: "The Hermit", image: "./public/images/the_hermit.png", arcana: "Major"},
    {id: 11, name: "Wheel of Fortune", image: "./public/images/wheel_of_fortune.png", arcana: "Major"},
    {id: 12, name: "Justice", image: "./public/images/justice.png", arcana: "Major"},
    {id: 13, name: "The Hanged Man", image: "./public/images/the_hanged_man.png", arcana: "Major"},
    {id: 14, name: "Death", image: "./public/images/death.png", arcana: "Major"},
    {id: 15, name: "Temperance", image: "./public/images/temperance.png", arcana: "Major"},
    {id: 16, name: "The Devil", image: "./public/images/the_devil.png", arcana: "Major"},
    {id: 17, name: "The Tower", image: "./public/images/the_tower.png", arcana: "Major"},
    {id: 18, name: "The Star", image: "./public/images/the_star.png", arcana: "Major"},
    {id: 19, name: "The Moon", image: "./public/images/the_moon.png", arcana: "Major"},
    {id: 20, name: "The Sun", image: "./public/images/the_sun.png", arcana: "Major"},
    {id: 21, name: "Judgement", image: "./public/images/judgement.png", arcana: "Major"},
    {id: 22, name: "The World", image: "./public/images/the_world.png", arcana: "Major"},

    // Minor Arcana
    // Suit: Wands
    {id: 23, name: "Ace of Wands", image: "./public/images/ace_of_wands.png", arcana: "Minor"},
    {id: 24, name: "Two of Wands", image: "./public/images/two_of_wands.png", arcana: "Minor"},
    {id: 25, name: "Three of Wands", image: "./public/images/three_of_wands.png", arcana: "Minor"},
    {id: 26, name: "Four of Wands", image: "./public/images/four_of_wands.png", arcana: "Minor"},
    {id: 27, name: "Five of Wands", image: "./public/images/five_of_wands.png", arcana: "Minor"},
    {id: 28, name: "Six of Wands", image: "./public/images/six_of_wands.png", arcana: "Minor"},
    {id: 29, name: "Seven of Wands", image: "./public/images/seven_of_wands.png", arcana: "Minor"},
    {id: 30, name: "Eight of Wands", image: "./public/images/eight_of_wands.png", arcana: "Minor"},
    {id: 31, name: "Nine of Wands", image: "./public/images/nine_of_wands.png", arcana: "Minor"},
    {id: 32, name: "Ten of Wands", image: "./public/images/ten_of_wands.png", arcana: "Minor"},
    {id: 33, name: "Page of Wands", image: "./public/images/page_of_wands.png", arcana: "Minor"},
    {id: 34, name: "Knight of Wands", image: "./public/images/knight_of_wands.png", arcana: "Minor"},
    {id: 35, name: "Queen of Wands", image: "./public/images/queen_of_wands.png", arcana: "Minor"},
    {id: 36, name: "King of Wands", image: "./public/images/king_of_wands.png", arcana: "Minor"},

    // Suit: Cups
    {id: 37, name: "Ace of Cups", image: "./public/images/ace_of_cups.png", arcana: "Minor"},
    {id: 38, name: "Two of Cups", image: "./public/images/two_of_cups.png", arcana: "Minor"},
    {id: 39, name: "Three of Cups", image: "./public/images/three_of_cups.png", arcana: "Minor"},
    {id: 40, name: "Four of Cups", image: "./public/images/four_of_cups.png", arcana: "Minor"},
    {id: 41, name: "Five of Cups", image: "./public/images/five_of_cups.png", arcana: "Minor"},
    {id: 42, name: "Six of Cups", image: "./public/images/six_of_cups.png", arcana: "Minor"},
    {id: 43, name: "Seven of Cups", image: "./public/images/seven_of_cups.png", arcana: "Minor"},
    {id: 44, name: "Eight of Cups", image: "./public/images/eight_of_cups.png", arcana: "Minor"},
    {id: 45, name: "Nine of Cups", image: "./public/images/nine_of_cups.png", arcana: "Minor"},
    {id: 46, name: "Ten of Cups", image: "./public/images/ten_of_cups.png", arcana: "Minor"},
    {id: 47, name: "Page of Cups", image: "./public/images/page_of_cups.png", arcana: "Minor"},
    {id: 48, name: "Knight of Cups", image: "./public/images/knight_of_cups.png", arcana: "Minor"},
    {id: 49, name: "Queen of Cups", image: "./public/images/queen_of_cups.png", arcana: "Minor"},
    {id: 50, name: "King of Cups", image: "./public/images/king_of_cups.png", arcana: "Minor"},

    // Suit: Swords
    {id: 51, name: "Ace of Swords", image: "./public/images/ace_of_swords.png", arcana: "Minor"},
    {id: 52, name: "Two of Swords", image: "./public/images/two_of_swords.png", arcana: "Minor"},
    {id: 53, name: "Three of Swords", image: "./public/images/three_of_swords.png", arcana: "Minor"},
    {id: 54, name: "Four of Swords", image: "./public/images/four_of_swords.png", arcana: "Minor"},
    {id: 55, name: "Five of Swords", image: "./public/images/five_of_swords.png", arcana: "Minor"},
    {id: 56, name: "Six of Swords", image: "./public/images/six_of_swords.png", arcana: "Minor"},
    {id: 57, name: "Seven of Swords", image: "./public/images/seven_of_swords.png", arcana: "Minor"},
    {id: 58, name: "Eight of Swords", image: "./public/images/eight_of_swords.png", arcana: "Minor"},
    {id: 59, name: "Nine of Swords", image: "./public/images/nine_of_swords.png", arcana: "Minor"},
    {id: 60, name: "Ten of Swords", image: "./public/images/ten_of_swords.png", arcana: "Minor"},
    {id: 61, name: "Page of Swords", image: "./public/images/page_of_swords.png", arcana: "Minor"},
    {id: 62, name: "Knight of Swords", image: "./public/images/knight_of_swords.png", arcana: "Minor"},
    {id: 63, name: "Queen of Swords", image: "./public/images/queen_of_swords.png", arcana: "Minor"},
    {id: 64, name: "King of Swords", image: "./public/images/king_of_swords.png", arcana: "Minor"},

    // Suit: Pentacles
    {id: 65, name: "Ace of Pentacles", image: "./public/images/ace_of_pentacles.png", arcana: "Minor"},
    {id: 66, name: "Two of Pentacles", image: "./public/images/two_of_pentacles.png", arcana: "Minor"},
    {id: 67, name: "Three of Pentacles", image: "./public/images/three_of_pentacles.png", arcana: "Minor"},
    {id: 68, name: "Four of Pentacles", image: "./public/images/four_of_pentacles.png", arcana: "Minor"},
    {id: 69, name: "Five of Pentacles", image: "./public/images/five_of_pentacles.png", arcana: "Minor"},
    {id: 70, name: "Six of Pentacles", image: "./public/images/six_of_pentacles.png", arcana: "Minor"},
    {id: 71, name: "Seven of Pentacles", image: "./public/images/seven_of_pentacles.png", arcana: "Minor"},
    {id: 72, name: "Eight of Pentacles", image: "./public/images/eight_of_pentacles.png", arcana: "Minor"},
    {id: 73, name: "Nine of Pentacles", image: "./public/images/nine_of_pentacles.png", arcana: "Minor"},
    {id: 74, name: "Ten of Pentacles", image: "./public/images/ten_of_pentacles.png", arcana: "Minor"},
    {id: 75, name: "Page of Pentacles", image: "./public/images/page_of_pentacles.png", arcana: "Minor"},
    {id: 76, name: "Knight of Pentacles", image: "./public/images/knight_of_pentacles.png", arcana: "Minor"},
    {id: 77, name: "Queen of Pentacles", image: "./public/images/queen_of_pentacles.png", arcana: "Minor"},
    {id: 78, name: "King of Pentacles", image: "./public/images/king_of_pentacles.png", arcana: "Minor"},
];