export const tarotDeck = [
    // Major Arcana
    {id: 1, name: "The Fool", image: "./images/the_fool.png", arcana: "Major", meaning: "Folly, mania, extravagance, indoxication, delirium, frenzy, bewrayment."},
    {id: 2, name: "The Magician", image: "./images/the_magician.png", arcana: "Major", meaning: "Skill, diplomacy, address, sickness, pain, loss, disaster, self-confidence, represents the Querant (if male)"},
    {id: 3, name: "The High Priestess", image: "./images/the_high_priestess.png", arcana: "Major", meaning: "Secrets, mystery, the future as yet unrevealed, the woman who interest the Querant (if male); the Querant (if female) silence, tenacity; wisdom, science."},
    {id: 4, name: "The Empress", image: "./images/the_empress.png", arcana: "Major", meaning: "Fruitfulness, initiative, action, long days, clandestine, the unknown, difficulty, doubt, ignorance."},
    {id: 5, name: "The Emperor", image: "./images/the_emperor.png", arcana: "Major", meaning: "Stability, power, aid, protection, a great person, conviction, reason."},
    {id: 6, name: "The Hierophant", image: "./images/the_hierophant.png", arcana: "Major", meaning: "Marriage alliance, captivity, servitude, mercy and goodness, inspiration, the man to whom the Querant has recourse."},
    {id: 7, name: "The Lovers", image: "./images/the_lovers.png", arcana: "Major", meaning: "Attraction, love, beauty, trials overcome."},
    {id: 8, name: "The Chariot", image: "./images/the_chariot.png", arcana: "Major", meaning: "Succor, providence, also war, triumph, presumption, vengeance, trouble."},
    {id: 9, name: "Strength", image: "./images/strength.png", arcana: "Major", meaning: "Power, energy, action, courage, magnanimity"},
    {id: 10, name: "The Hermit", image: "./images/the_hermit.png", arcana: "Major", meaning: "Prudence, also and especially treason, dissimulation, corruption, roguery."},
    {id: 11, name: "Wheel of Fortune", image: "./images/wheel_of_fortune.png", arcana: "Major", meaning: "Destiny, fortune, success, luck, felicity."},
    {id: 12, name: "Justice", image: "./images/justice.png", arcana: "Major", meaning: "Equity, rightness, probity, executive."},
    {id: 13, name: "The Hanged Man", image: "./images/the_hanged_man.png", arcana: "Major", meaning: "Wisdom, trials, circumspection, discenrment, sacrifice, intuition, divination, prophecy."},
    {id: 14, name: "Death", image: "./images/death.png", arcana: "Major", meaning: "End, mortality, destruction, corruption."},
    {id: 15, name: "Temperance", image: "./images/temperance.png", arcana: "Major", meaning: "Economy, moderation, frugality, management, accommodation."},
    {id: 16, name: "The Devil", image: "./images/the_devil.png", arcana: "Major", meaning: "Ravage, violence, force, vehemence, extraordinary efforts, fatality, that which is predestined but not for this reason evil."},
    {id: 17, name: "The Tower", image: "./images/the_tower.png", arcana: "Major", meaning: "Misery, distress, ruin, indigence, adversity, calamity, disgrace, deception."},
    {id: 18, name: "The Star", image: "./images/the_star.png", arcana: "Major", meaning: "Loss, theft, privation, abandonment, although another reading suggests hope and bright prospects in the future."},
    {id: 19, name: "The Moon", image: "./images/the_moon.png", arcana: "Major", meaning: "Hidden enemies, danger, calumny, darkness, terror, deception, error."},
    {id: 20, name: "The Sun", image: "./images/the_sun.png", arcana: "Major", meaning: "Material happiness, fortunate marriage, contentment."},
    {id: 21, name: "Judgement", image: "./images/judgement.png", arcana: "Major", meaning: "Change of position, renewal, outcome."},
    {id: 22, name: "The World", image: "./images/the_world.png", arcana: "Major", meaning: "Assured success, route, voyage, emigration, flight, change of place."},

    // Minor Arcana
    // Suit: Wands
    {id: 23, name: "Ace of Wands", image: "./images/ace_of_wands.png", arcana: "Minor"},
    {id: 24, name: "Two of Wands", image: "./images/two_of_wands.png", arcana: "Minor"},
    {id: 25, name: "Three of Wands", image: "./images/three_of_wands.png", arcana: "Minor"},
    {id: 26, name: "Four of Wands", image: "./images/four_of_wands.png", arcana: "Minor"},
    {id: 27, name: "Five of Wands", image: "./images/five_of_wands.png", arcana: "Minor"},
    {id: 28, name: "Six of Wands", image: "./images/six_of_wands.png", arcana: "Minor"},
    {id: 29, name: "Seven of Wands", image: "./images/seven_of_wands.png", arcana: "Minor"},
    {id: 30, name: "Eight of Wands", image: "./images/eight_of_wands.png", arcana: "Minor"},
    {id: 31, name: "Nine of Wands", image: "./images/nine_of_wands.png", arcana: "Minor"},
    {id: 32, name: "Ten of Wands", image: "./images/ten_of_wands.png", arcana: "Minor"},
    {id: 33, name: "Page of Wands", image: "./images/page_of_wands.png", arcana: "Minor"},
    {id: 34, name: "Knight of Wands", image: "./images/knight_of_wands.png", arcana: "Minor"},
    {id: 35, name: "Queen of Wands", image: "./images/queen_of_wands.png", arcana: "Minor"},
    {id: 36, name: "King of Wands", image: "./images/king_of_wands.png", arcana: "Minor"},

    // Suit: Cups
    {id: 37, name: "Ace of Cups", image: "./images/ace_of_cups.png", arcana: "Minor"},
    {id: 38, name: "Two of Cups", image: "./images/two_of_cups.png", arcana: "Minor"},
    {id: 39, name: "Three of Cups", image: "./images/three_of_cups.png", arcana: "Minor"},
    {id: 40, name: "Four of Cups", image: "./images/four_of_cups.png", arcana: "Minor"},
    {id: 41, name: "Five of Cups", image: "./images/five_of_cups.png", arcana: "Minor"},
    {id: 42, name: "Six of Cups", image: "./images/six_of_cups.png", arcana: "Minor"},
    {id: 43, name: "Seven of Cups", image: "./images/seven_of_cups.png", arcana: "Minor"},
    {id: 44, name: "Eight of Cups", image: "./images/eight_of_cups.png", arcana: "Minor"},
    {id: 45, name: "Nine of Cups", image: "./images/nine_of_cups.png", arcana: "Minor"},
    {id: 46, name: "Ten of Cups", image: "./images/ten_of_cups.png", arcana: "Minor"},
    {id: 47, name: "Page of Cups", image: "./images/page_of_cups.png", arcana: "Minor"},
    {id: 48, name: "Knight of Cups", image: "./images/knight_of_cups.png", arcana: "Minor"},
    {id: 49, name: "Queen of Cups", image: "./images/queen_of_cups.png", arcana: "Minor"},
    {id: 50, name: "King of Cups", image: "./images/king_of_cups.png", arcana: "Minor"},

    // Suit: Swords
    {id: 51, name: "Ace of Swords", image: "./images/ace_of_swords.png", arcana: "Minor"},
    {id: 52, name: "Two of Swords", image: "./images/two_of_swords.png", arcana: "Minor"},
    {id: 53, name: "Three of Swords", image: "./images/three_of_swords.png", arcana: "Minor"},
    {id: 54, name: "Four of Swords", image: "./images/four_of_swords.png", arcana: "Minor"},
    {id: 55, name: "Five of Swords", image: "./images/five_of_swords.png", arcana: "Minor"},
    {id: 56, name: "Six of Swords", image: "./images/six_of_swords.png", arcana: "Minor"},
    {id: 57, name: "Seven of Swords", image: "./images/seven_of_swords.png", arcana: "Minor"},
    {id: 58, name: "Eight of Swords", image: "./images/eight_of_swords.png", arcana: "Minor"},
    {id: 59, name: "Nine of Swords", image: "./images/nine_of_swords.png", arcana: "Minor"},
    {id: 60, name: "Ten of Swords", image: "./images/ten_of_swords.png", arcana: "Minor"},
    {id: 61, name: "Page of Swords", image: "./images/page_of_swords.png", arcana: "Minor"},
    {id: 62, name: "Knight of Swords", image: "./images/knight_of_swords.png", arcana: "Minor"},
    {id: 63, name: "Queen of Swords", image: "./images/queen_of_swords.png", arcana: "Minor"},
    {id: 64, name: "King of Swords", image: "./images/king_of_swords.png", arcana: "Minor"},

    // Suit: Pentacles
    {id: 65, name: "Ace of Pentacles", image: "./images/ace_of_pentacles.png", arcana: "Minor"},
    {id: 66, name: "Two of Pentacles", image: "./images/two_of_pentacles.png", arcana: "Minor"},
    {id: 67, name: "Three of Pentacles", image: "./images/three_of_pentacles.png", arcana: "Minor"},
    {id: 68, name: "Four of Pentacles", image: "./images/four_of_pentacles.png", arcana: "Minor"},
    {id: 69, name: "Five of Pentacles", image: "./images/five_of_pentacles.png", arcana: "Minor"},
    {id: 70, name: "Six of Pentacles", image: "./images/six_of_pentacles.png", arcana: "Minor"},
    {id: 71, name: "Seven of Pentacles", image: "./images/seven_of_pentacles.png", arcana: "Minor"},
    {id: 72, name: "Eight of Pentacles", image: "./images/eight_of_pentacles.png", arcana: "Minor"},
    {id: 73, name: "Nine of Pentacles", image: "./images/nine_of_pentacles.png", arcana: "Minor"},
    {id: 74, name: "Ten of Pentacles", image: "./images/ten_of_pentacles.png", arcana: "Minor"},
    {id: 75, name: "Page of Pentacles", image: "./images/page_of_pentacles.png", arcana: "Minor"},
    {id: 76, name: "Knight of Pentacles", image: "./images/knight_of_pentacles.png", arcana: "Minor"},
    {id: 77, name: "Queen of Pentacles", image: "./images/queen_of_pentacles.png", arcana: "Minor"},
    {id: 78, name: "King of Pentacles", image: "./images/king_of_pentacles.png", arcana: "Minor"},
];