export const tarotDeck = [
    // Major Arcana
    {id: 1, name: "The Fool", image: "./images/the_fool.png", arcana: "Major", meaning: "Innocence, new beginnings, free spirit.", meaningReversed: "Recklessness, taken advantage of, inconsideration."},
    {id: 2, name: "The Magician", image: "./images/the_magician.png", arcana: "Major", meaning: "Willpoer, desire, creation, manifestation.", meaningReversed: "Trickery, illusions, out of touch."},
    {id: 3, name: "The High Priestess", image: "./images/the_high_priestess.png", arcana: "Major", meaning: "Intuitive, unconscious, inner voice.", meaningReversed: "Lack of center, lost inner voice, repressed feelings."},
    {id: 4, name: "The Empress", image: "./images/the_empress.png", arcana: "Major", meaning: "Motherhood, fertility, nature.", meaningReversed: "Dependence, smothering, emptiness, nosiness"},
    {id: 5, name: "The Emperor", image: "./images/the_emperor.png", arcana: "Major", meaning: "Authority, structure, control, fatherhood.", meaningReversed: "Tyranny, rigidity, coldness."},
    {id: 6, name: "The Hierophant", image: "./images/the_hierophant.png", arcana: "Major", meaning: "Tradition, conformity, morality, ethics.", meaningReversed: "Rebellion, subversiveness, new approaches."},
    {id: 7, name: "The Lovers", image: "./images/the_lovers.png", arcana: "Major", meaning: "Partnerships, duality, union.", meaningReversed: "Loss of balance, one-sidedness, disharmony."},
    {id: 8, name: "The Chariot", image: "./images/the_chariot.png", arcana: "Major", meaning: "Direction, control, willpower.", meaningReversed: "Lack of control, lack of direction, aggression."},
    {id: 9, name: "Strength", image: "./images/strength.png", arcana: "Major", meaning: "Inner strength, bravery, compassion, focus.", meaningReversed: "Self-doubt, weakness, insecurity."},
    {id: 10, name: "The Hermit", image: "./images/the_hermit.png", arcana: "Major", meaning: "Contemplation, the search for truth, inner guidance.", meaningReversed: "Loneliness, isolation, losing your way."},
    {id: 11, name: "Wheel of Fortune", image: "./images/wheel_of_fortune.png", arcana: "Major", meaning: "Change, cycles, inevitable fate.", meaningReversed: "No control, clinging to control, bad luck."},
    {id: 12, name: "Justice", image: "./images/justice.png", arcana: "Major", meaning: "Cause and effect, clarity, truth.", meaningReversed: "Dishonesty, unaccountability, unfairness."},
    {id: 13, name: "The Hanged Man", image: "./images/the_hanged_man.png", arcana: "Major", meaning: "Sacrifice, release, martyrdom.", meaningReversed: "Stalling, needless sacrifice, fear of sacrifice."},
    {id: 14, name: "Death", image: "./images/death.png", arcana: "Major", meaning: "End of cycle, beginnings, change, metamorphosis.", meaningReversed: "Fear of change, holding on, stagnation, decay."},
    {id: 15, name: "Temperance", image: "./images/temperance.png", arcana: "Major", meaning: "Middle path, patience, finding meaning.", meaningReversed: "Extremes, excess, lack of balance."},
    {id: 16, name: "The Devil", image: "./images/the_devil.png", arcana: "Major", meaning: "Addiction, materialism, playfulness.", meaningReversed: "Freedom, release, restoring control."},
    {id: 17, name: "The Tower", image: "./images/the_tower.png", arcana: "Major", meaning: "Sudden upheaval, broken pride, disaster.", meaningReversed: "Disaster avoided, delayed disaster, fear of suffering."},
    {id: 18, name: "Yhr Star", image: "./images/the_star.png", arcana: "Major", meaning: "Hope, faith, rejuvenation.", meaningReversed: "Faithlessness, discouragement, insecurity."},
    {id: 19, name: "The Moon", image: "./images/the_moon.png", arcana: "Major", meaning: "Unconscious, illusions, intuition.", meaningReversed: "Confusion, fear, misinterpretation."},
    {id: 20, name: "The Sun", image: "./images/the_sun.png", arcana: "Major", meaning: "Joy, success, celebration, positivity.", meaningReversed: "Negativity, depression, sadness."},
    {id: 21, name: "Judgement", image: "./images/judgement.png", arcana: "Major", meaning: "Reflection, reckoning, awakening.", meaningReversed: "Lack of self-awareness, doubt, self-loathing."},
    {id: 22, name: "The World", image: "./images/the_world.png", arcana: "Major", meaning: "Fulfillment, harmony, completion.", meaningReversed: "Incompletion, no closure."},

    // Minor Arcana
    // Suit: Wands
    {id: 23, name: "Ace of Wands", image: "./images/ace_of_wands.png", arcana: "Minor", meaning: "Creation, willpower, inspiration, desire.", meaningReversed: "Lack of energy, lack of passion, boredom."},
    {id: 24, name: "Two of Wands", image: "./images/two_of_wands.png", arcana: "Minor", meaning: "Planning, making decisions, leaving home.", meaningReversed: "Fear of change, playing it safe, bad planning."},
    {id: 25, name: "Three of Wands", image: "./images/three_of_wands.png", arcana: "Minor", meaning: "Looking ahead, expansion, rapid growth.", meaningReversed: "Obstacles, delays, frustration."},
    {id: 26, name: "Four of Wands", image: "./images/four_of_wands.png", arcana: "Minor", meaning: "Community, home, celebration.", meaningReversed: "Lack of support, transience, home conflicts."},
    {id: 27, name: "Five of Wands", image: "./images/five_of_wands.png", arcana: "Minor", meaning: "Competition, rivalry, conflict.", meaningReversed: "Avoiding conflict, respecting differences."},
    {id: 28, name: "Six of Wands", image: "./images/six_of_wands.png", arcana: "Minor", meaning: "Victory, success, public reward.", meaningReversed: "Excess pride, lack of recognition, punishment."},
    {id: 29, name: "Seven of Wands", image: "./images/seven_of_wands.png", arcana: "Minor", meaning: "Perserverance, defensive, maintaining control.", meaningReversed: "Give up, destroyed confidence, overwhelmed."},
    {id: 30, name: "Eight of Wands", image: "./images/eight_of_wands.png", arcana: "Minor", meaning: "Rapid action, movement, quick decisions.", meaningReversed: "Panic, waiting, slowdown."},
    {id: 31, name: "Nine of Wands", image: "./images/nine_of_wands.png", arcana: "Minor", meaning: "Resilience, grit, last stand.", meaningReversed: "Exhaustion, fatigue, questioning motivations."},
    {id: 32, name: "Ten of Wands", image: "./images/ten_of_wands.png", arcana: "Minor", meaning: "Accomplishment, responsibility, burden.", meaningReversed: "Inibility to delegate, overstressed, burnt out."},
    {id: 33, name: "Page of Wands", image: "./images/page_of_wands.png", arcana: "Minor", meaning: "Exploration, excitement, freedom.", meaningReversed: "Lack of direction, procrastination, creating conflict."},
    {id: 34, name: "Knight of Wands", image: "./images/knight_of_wands.png", arcana: "Minor", meaning: "Action, adventure, fearlessness.", meaningReversed: "Anger, impulsiveness, recklessness."},
    {id: 35, name: "Queen of Wands", image: "./images/queen_of_wands.png", arcana: "Minor", meaning: "Courage, determination, joy.", meaningReversed: "Selfishness, jealousy, insecurities."},
    {id: 36, name: "King of Wands", image: "./images/king_of_wands.png", arcana: "Minor", meaning: "Big picture, leader, overcoming challenges.", meaningReversed: "Impulsive, overbearing, unachievable expectations."},

    // Suit: Cups
    {id: 37, name: "Ace of Cups", image: "./images/ace_of_cups.png", arcana: "Minor", meaning: "New feelings, spirituality, intuition.", meaningReversed: "Emotional loss, blocked creativity, emptiness."},
    {id: 38, name: "Two of Cups", image: "./images/two_of_cups.png", arcana: "Minor", meaning: "Unity, partnership, connection.", meaningReversed: "Imbalance, broken communication, tension."},
    {id: 39, name: "Three of Cups", image: "./images/three_of_cups.png", arcana: "Minor", meaning: "Friendship, community, happiness.", meaningReversed: "Overindulgence, gossip, isolation."},
    {id: 40, name: "Four of Cups", image: "./images/four_of_cups.png", arcana: "Minor", meaning: "Apathy, contemplation, disconnectedness.", meaningReversed: "Sudden awareness, choosing happiness, acceptance."},
    {id: 41, name: "Five of Cups", image: "./images/five_of_cups.png", arcana: "Minor", meaning: "Loss, grief, self-pity.", meaningReversed: "Acceptance, moving on, finding peace."},
    {id: 42, name: "Six of Cups", image: "./images/six_of_cups.png", arcana: "Minor", meaning: "Familiarity, happy memories, healing.", meaningReversed: "Moving forward, leaving home, independence."},
    {id: 43, name: "Seven of Cups", image: "./images/seven_of_cups.png", arcana: "Minor", meaning: "Searching for purpose, choices, daydreaming.", meaningReversed: "Lack of purpose, diversion, confusion."},
    {id: 44, name: "Eight of Cups", image: "./images/eight_of_cups.png", arcana: "Minor", meaning: "Walking away, disillusionment, leaving behind.", meaningReversed: "Avoidance, fear of change, fear of loss."},
    {id: 45, name: "Nine of Cups", image: "./images/nine_of_cups.png", arcana: "Minor", meaning: "Satisfaction, emotional stability, luxury.", meaningReversed: "Lack of inner joy, smugness, dissatisfaction."},
    {id: 46, name: "Ten of Cups", image: "./images/ten_of_cups.png", arcana: "Minor", meaning: "Inner happiness, fulfillment, dreams coming true.", meaningReversed: "Shattered dreams, broken family, domestic disharmony."},
    {id: 47, name: "Page of Cups", image: "./images/page_of_cups.png", arcana: "Minor", meaning: "Happy surprise, dreamer, sensitivity.", meaningReversed: "Emotional immaturity, insecurity, disappointment."},
    {id: 48, name: "Knight of Cups", image: "./images/knight_of_cups.png", arcana: "Minor", meaning: "Following, idealist, romantic.", meaningReversed: "Moodiness, disappointment."},
    {id: 49, name: "Queen of Cups", image: "./images/queen_of_cups.png", arcana: "Minor", meaning: "Compassion, calm, comfort.", meaningReversed: "Martyrdom, insecurity, dependence."},
    {id: 50, name: "King of Cups", image: "./images/king_of_cups.png", arcana: "Minor", meaning: "Compassion, control, balance.", meaningReversed: "Coldness, moodiness, bad advice."},

    // Suit: Swords
    {id: 51, name: "Ace of Swords", image: "./images/ace_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 52, name: "Two of Swords", image: "./images/two_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 53, name: "Three of Swords", image: "./images/three_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 54, name: "Four of Swords", image: "./images/four_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 55, name: "Five of Swords", image: "./images/five_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 56, name: "Six of Swords", image: "./images/six_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 57, name: "Seven of Swords", image: "./images/seven_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 58, name: "Eight of Swords", image: "./images/eight_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 59, name: "Nine of Swords", image: "./images/nine_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 60, name: "Ten of Swords", image: "./images/ten_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 61, name: "Page of Swords", image: "./images/page_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 62, name: "Knight of Swords", image: "./images/knight_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 63, name: "Queen of Swords", image: "./images/queen_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 64, name: "King of Swords", image: "./images/king_of_swords.png", arcana: "Minor", meaning: "", meaningReversed: ""},

    // Suit: Pentacles
    {id: 65, name: "Ace of Pentacles", image: "./images/ace_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 66, name: "Two of Pentacles", image: "./images/two_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 67, name: "Three of Pentacles", image: "./images/three_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 68, name: "Four of Pentacles", image: "./images/four_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 69, name: "Five of Pentacles", image: "./images/five_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 70, name: "Six of Pentacles", image: "./images/six_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 71, name: "Seven of Pentacles", image: "./images/seven_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 72, name: "Eight of Pentacles", image: "./images/eight_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 73, name: "Nine of Pentacles", image: "./images/nine_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 74, name: "Ten of Pentacles", image: "./images/ten_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 75, name: "Page of Pentacles", image: "./images/page_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 76, name: "Knight of Pentacles", image: "./images/knight_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 77, name: "Queen of Pentacles", image: "./images/queen_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
    {id: 78, name: "King of Pentacles", image: "./images/king_of_pentacles.png", arcana: "Minor", meaning: "", meaningReversed: ""},
];